### ISSUE TITLE
no migration file

### ISSUE THREAD

**Issue by MatthiasHertel** [avinashn/Ajax-CRUD-example-in-laravel#1]
to build this app from scratch u need a migration, before u can setup a database in the e.g. homestead.yaml and run the `vagrant provision` command on CLI

save the gist below under:
`database/migrations/$timestamp$_create_ds_table.php`

or run the artisan command on CLI:

```bash
vagrant@homestead:~/Code/ajax$ php artisan make:migration create_ds_table
Created Migration: 2016_08_25_101156_create_ds_table
```

and paste the code below 

```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('ds', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
```

**Comment by avinashn** [comment]
Added the missed migration file in the latest commit.

https://github.com/avinashn/Ajax-CRUD-example-in-laravel/blob/master/database/migrations/2014_10_12_000000_create_ds_table.php

**Comment by MatthiasHertel** [comment]
dont forget to explain it in the readme.md

**Comment by avinashn** [comment]
updated readme too
