### ISSUE TITLE
Parameter _token

### ISSUE THREAD

**Issue by SergeyKuzmenko** [avinashn/Ajax-CRUD-example-in-laravel#6]
Hi! 
I do not understand, why you are passing the POST parameter "_token"? Where in the backend is it checked?

**Comment by CaddyDz** [comment]
Hi @SergeyKuzmenko 
`_token` is a session generated code to prevent CSRF Attacks, it is passed as per the [documentation](https://laravel.com/docs/5.8/csrf#csrf-x-csrf-token)
